---
- name: Install Docker on Debian 12 and ensure it is running
  hosts: all
  become: yes  # Use sudo to execute tasks as root
  tasks:
    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
    
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
    
    - name: Add Docker’s official GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    
    - name: Add Docker APT repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable
        state: present
        update_cache: yes
    
    - name: Install Docker CE
      ansible.builtin.apt:
        name: docker-ce
        state: present

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes
